spring:
  # session 配置
  session:
      store-type: redis
      # 过期时间 30天
      timeout: 2592000
  profiles:
    active: local
  application:
    name: lin-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lin_ai_code_mother
    username: root
    password: root
  # 配置关闭超时时间
  lifecycle:
    timeout-per-shutdown-phase: 60s
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      username: root
      password:
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie过期时间 30天
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi ????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lin.linaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

